# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_auto_20170511_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerousWaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=200)),
                ('amount_generated', models.PositiveIntegerField()),
                ('type_condition', models.TextField()),
                ('action', models.TextField()),
                ('amount_stored', models.PositiveIntegerField()),
                ('date_last_medition', models.DateField()),
                ('observations', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='dangerouswaste',
            name='wastes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dangerous_waste.Waste'),
        ),
    ]
