# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dangerous_waste', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waste',
            old_name='date_last_medition',
            new_name='date_last_measure',
        ),
    ]
