# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangerous_waste', '0003_auto_20170515_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dangerouswaste',
            options={'verbose_name': 'Desecho Peligroso', 'verbose_name_plural': 'Desechos Peligrosos'},
        ),
        migrations.AlterModelOptions(
            name='waste',
            options={'verbose_name': 'Residuo', 'verbose_name_plural': 'Residuos'},
        ),
        migrations.AlterField(
            model_name='waste',
            name='action',
            field=models.TextField(verbose_name='Acción de manejo (Clasificación)'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='amount_generated',
            field=models.PositiveIntegerField(verbose_name='Cantidad Generada(t)'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='amount_stored',
            field=models.PositiveIntegerField(verbose_name='Cantidad almacenada (t)'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='classification',
            field=models.CharField(max_length=200, verbose_name='Clasificacion'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='date_last_measure',
            field=models.DateField(verbose_name='Fecha de última medición'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='observations',
            field=models.TextField(verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='type_condition',
            field=models.TextField(verbose_name='Tipo y condiciones de almacenamiento'),
        ),
        migrations.AlterField(
            model_name='waste',
            name='waste',
            field=models.CharField(max_length=100, verbose_name='Desecho'),
        ),
    ]
