# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dangerous_waste', '0004_auto_20170515_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangerouswaste',
            name='airport',
            field=models.CharField(max_length=200, verbose_name='Aeropuerto'),
        ),
        migrations.AlterField(
            model_name='dangerouswaste',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de elaboracion'),
        ),
        migrations.AlterField(
            model_name='dangerouswaste',
            name='made_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Elaborado por'),
        ),
    ]
