# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=picture.models.url),
        ),
    ]
