# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_auto_20170509_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
