# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picture.models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=100, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=picture.models.url, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='image',
            name='up_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Subido por'),
        ),
    ]
