# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170403_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='upload/', verbose_name='Imagen'),
        ),
    ]
