# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20170509_1945'),
        ('account', '0002_auto_20170509_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='model.Area'),
            preserve_default=False,
        ),
    ]
