# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 03:16
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170403_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.url, verbose_name='Imagen'),
        ),
    ]
