# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170511_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('W', 'Femenino'), ('U', 'Sin definir')], default='U', max_length=1, verbose_name='Genero'),
        ),
    ]
