# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CGA', 'Consejo de Gestion Ambiental'), ('otros', 'Otros Documentos')], max_length=5, verbose_name='Tipo de documento')),
                ('pub_date', models.DateField(auto_now=True)),
                ('file', models.FileField(upload_to='', verbose_name='Fichero')),
            ],
            options={
                'verbose_name': 'Bibliografia',
                'verbose_name_plural': 'Bibliografias',
            },
        ),
    ]
