# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='document_type',
            field=models.CharField(choices=[('CGA', 'Consejo de Gestion Ambiental'), ('Otros', 'Otros Documentos')], max_length=5, verbose_name='Tipo de documento'),
        ),
    ]
