# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import model.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='ModelR01PG01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[model.models.validate_year], verbose_name='año')),
                ('environmental_aspects', models.TextField(verbose_name='Aspectos Ambientales')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='fecha de publicación')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Area')),
            ],
            options={
                'verbose_name': 'Modelo R01/PG.190-01',
                'verbose_name_plural': 'Modelos R01/PG.190-01',
            },
        ),
    ]
