# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import model.models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelr01pg01',
            name='year',
            field=models.IntegerField(validators=[model.models.validate_year], verbose_name='año'),
        ),
    ]
