# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20170403_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelr01pg01',
            options={'verbose_name': 'Modelo R01/PG.190-01', 'verbose_name_plural': 'Modelos R01/PG.190-01'},
        ),
    ]
