# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20170509_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField()),
                ('law', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=100)),
                ('environmental_aspects', models.TextField()),
            ],
        ),
    ]
