# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20170511_0124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LawRequirements',
            new_name='LawRequirement',
        ),
    ]
