# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170511_0327'),
        ('model', '0006_emergencyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha de elaboracion')),
                ('summary', models.TextField(verbose_name='Sumario')),
                ('evaluation', models.IntegerField(verbose_name='Evaluacion')),
            ],
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='datetime',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='description',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='no',
            field=models.IntegerField(unique=True, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='place',
            field=models.CharField(max_length=100, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='report',
            field=models.CharField(choices=[('e', 'Situacion de emergencia'), ('a', 'Accidente'), ('r', 'Real'), ('s', 'Simulacro o Ejercicio')], default='s', max_length=1, verbose_name='Reporte'),
        ),
        migrations.CreateModel(
            name='RealAnalysis',
            fields=[
                ('analysis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.Analysis')),
                ('affections', models.TextField(verbose_name='Afectaciones')),
                ('measures', models.TextField(verbose_name='Medidas')),
                ('first_time', models.BooleanField(default=False, verbose_name='Es la primera vez')),
                ('cause', models.TextField(verbose_name='Causa')),
            ],
            bases=('model.analysis',),
        ),
        migrations.CreateModel(
            name='SimulationAnalysis',
            fields=[
                ('analysis_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.Analysis')),
                ('is_necessary_check', models.BooleanField(default=False, verbose_name='Es necesario revisar')),
                ('specify', models.TextField(blank=True, verbose_name='Especificaciones')),
                ('participants', models.FileField(upload_to='', verbose_name='Participantes')),
            ],
            bases=('model.analysis',),
        ),
        migrations.AddField(
            model_name='analysis',
            name='make_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Elaborado por'),
        ),
    ]
