# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20170511_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='emergency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='model.EmergencyReport', verbose_name='Reporte de mergencia'),
            preserve_default=False,
        ),
    ]
