# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import model.models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_analysis_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='emergency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.EmergencyReport', verbose_name='Reporte de emergencia'),
        ),
        migrations.AlterField(
            model_name='simulationanalysis',
            name='participants',
            field=models.FileField(blank=True, upload_to=model.models.url_analysis, verbose_name='Participantes'),
        ),
    ]
