# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import model.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170511_0327'),
        ('model', '0009_auto_20170511_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[model.models.validate_year])),
                ('date', models.DateField(auto_now=True)),
                ('reception_way', models.CharField(max_length=200)),
                ('type_communication', models.CharField(choices=[('i', 'interna'), ('e', 'externa')], max_length=1)),
                ('contact_data', models.TextField()),
                ('info_content', models.TextField()),
                ('adopted_decision', models.CharField(max_length=200)),
                ('distribution_date', models.DateField()),
                ('emission_path', models.CharField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Area')),
                ('register_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
    ]
