# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_auto_20170511_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name': 'Analisis', 'verbose_name_plural': 'Analisis'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='communication',
            options={'verbose_name': 'Comunicacion', 'verbose_name_plural': 'Comunicaciones'},
        ),
        migrations.AlterModelOptions(
            name='emergencyreport',
            options={'verbose_name': 'Reporte de Emergencia', 'verbose_name_plural': 'Reportes de Emergencia'},
        ),
        migrations.AlterModelOptions(
            name='lawrequirement',
            options={'verbose_name': 'Requerimiento Legal', 'verbose_name_plural': 'Requerimientos Legales'},
        ),
        migrations.AlterModelOptions(
            name='modelr01pg01',
            options={'verbose_name': 'Aspecto Ambiental', 'verbose_name_plural': 'Aspectos Ambientales'},
        ),
        migrations.AlterModelOptions(
            name='realanalysis',
            options={'verbose_name': 'Analisis de Situaciones Reales', 'verbose_name_plural': 'Analisis de una Situacion Real'},
        ),
        migrations.AlterModelOptions(
            name='simulationanalysis',
            options={'verbose_name': 'Analisis de Simulacro o Ejercicio', 'verbose_name_plural': 'Analisis de Simulacros o Ejercicios'},
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='airport',
            field=models.CharField(default='Jose Marti', max_length=150, verbose_name='Aereopuerto'),
            preserve_default=False,
        ),
    ]
