# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_auto_20170521_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalAspectMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environmental_impact', models.CharField(max_length=150, verbose_name='Impacto Ambiental Asociado')),
                ('consume', models.CharField(blank=True, max_length=100, verbose_name='Consumo')),
                ('frequency', models.PositiveIntegerField(verbose_name='Frecuencia')),
                ('probability', models.PositiveIntegerField(verbose_name='Probabilidad')),
                ('severity', models.PositiveIntegerField(verbose_name='Gravedad')),
                ('environment_aspect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='model.ModelR01PG01', verbose_name='Aspecto Ambiental')),
            ],
            options={
                'verbose_name': 'Matriz de Aspecto Ambiental',
                'verbose_name_plural': 'Matrices de Aspectos Ambientales',
            },
        ),
    ]
