# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_environmentalaspectmatrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalaspectmatrix',
            name='character',
            field=models.CharField(choices=[('-', 'Negativo'), ('+', 'Positivo')], default='-', max_length=1, verbose_name='Caracter'),
            preserve_default=False,
        ),
    ]
