# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_environmentalaspectmatrix_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalaspectmatrix',
            name='activity',
            field=models.CharField(default='a', max_length=200, verbose_name='Actividad, Producto o servicio'),
            preserve_default=False,
        ),
    ]
