# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_auto_20170511_0327'),
        ('model', '0011_auto_20170511_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e', models.CharField(blank=True, choices=[('nc', 'Auditoría Nivel Central'), ('sgc', 'Auditoría al SGC'), ('z', 'Auditoría de la UEB Aeropuerto'), ('sga', 'Auditoría al SGA'), ('e', 'Auditoría de la Especialidad (UEB Nacionales)'), ('sgi', 'Auditoría al SGICH'), ('bv', 'Auditoría de Bureau Veritas'), ('ai', 'Auditoría Integrada')], max_length=3, verbose_name='Enero')),
                ('f', models.CharField(blank=True, choices=[('nc', 'Auditoría Nivel Central'), ('sgc', 'Auditoría al SGC'), ('z', 'Auditoría de la UEB Aeropuerto'), ('sga', 'Auditoría al SGA'), ('e', 'Auditoría de la Especialidad (UEB Nacionales)'), ('sgi', 'Auditoría al SGICH'), ('bv', 'Auditoría de Bureau Veritas'), ('ai', 'Auditoría Integrada')], max_length=3, verbose_name='Febrero')),
                ('ma', models.CharField(blank=True, choices=[('nc', 'Auditoría Nivel Central'), ('sgc', 'Auditoría al SGC'), ('z', 'Auditoría de la UEB Aeropuerto'), ('sga', 'Auditoría al SGA'), ('e', 'Auditoría de la Especialidad (UEB Nacionales)'), ('sgi', 'Auditoría al SGICH'), ('bv', 'Auditoría de Bureau Veritas'), ('ai', 'Auditoría Integrada')], max_length=3, verbose_name='Marzo')),
                ('ab', models.CharField(blank=True, choices=[('nc', 'Auditoría Nivel Central'), ('sgc', 'Auditoría al SGC'), ('z', 'Auditoría de la UEB Aeropuerto'), ('sga', 'Auditoría al SGA'), ('e', 'Auditoría de la Especialidad (UEB Nacionales)'), ('sgi', 'Auditoría al SGICH'), ('bv', 'Auditoría de Bureau Veritas'), ('ai', 'Auditoría Integrada')], max_length=3, verbose_name='Abril')),
                ('m', models.CharField(blank=True, choices=[('nc', 'Auditoría Nivel Central'), ('sgc', 'Auditoría al SGC'), ('z', 'Auditoría de la UEB Aeropuerto'), ('sga', 'Auditoría al SGA'), ('e', 'Auditoría de la Especialidad (UEB Nacionales)'), ('sgi', 'Auditoría al SGICH'), ('bv', 'Auditoría de Bureau Veritas'), ('ai', 'Auditoría Integrada')], max_length=3, verbose_name='Mayo')),
                ('j', models.CharField(blank=True, choices=[('nc', 'Auditoría Nivel Central'), ('sgc', 'Auditoría al SGC'), ('z', 'Auditoría de la UEB Aeropuerto'), ('sga', 'Auditoría al SGA'), ('e', 'Auditoría de la Especialidad (UEB Nacionales)'), ('sgi', 'Auditoría al SGICH'), ('bv', 'Auditoría de Bureau Veritas'), ('ai', 'Auditoría Integrada')], max_length=3, verbose_name='Junio')),
                ('ju', models.CharField(blank=True, choices=[('nc', 'Auditoría Nivel Central'), ('sgc', 'Auditoría al SGC'), ('z', 'Auditoría de la UEB Aeropuerto'), ('sga', 'Auditoría al SGA'), ('e', 'Auditoría de la Especialidad (UEB Nacionales)'), ('sgi', 'Auditoría al SGICH'), ('bv', 'Auditoría de Bureau Veritas'), ('ai', 'Auditoría Integrada')], max_length=3, verbose_name='Julio')),
                ('a', models.CharField(blank=True, choices=[('nc', 'Auditoría Nivel Central'), ('sgc', 'Auditoría al SGC'), ('z', 'Auditoría de la UEB Aeropuerto'), ('sga', 'Auditoría al SGA'), ('e', 'Auditoría de la Especialidad (UEB Nacionales)'), ('sgi', 'Auditoría al SGICH'), ('bv', 'Auditoría de Bureau Veritas'), ('ai', 'Auditoría Integrada')], max_length=3, verbose_name='Agosto')),
                ('s', models.CharField(blank=True, choices=[('nc', 'Auditoría Nivel Central'), ('sgc', 'Auditoría al SGC'), ('z', 'Auditoría de la UEB Aeropuerto'), ('sga', 'Auditoría al SGA'), ('e', 'Auditoría de la Especialidad (UEB Nacionales)'), ('sgi', 'Auditoría al SGICH'), ('bv', 'Auditoría de Bureau Veritas'), ('ai', 'Auditoría Integrada')], max_length=3, verbose_name='Septiembre')),
                ('o', models.CharField(blank=True, choices=[('nc', 'Auditoría Nivel Central'), ('sgc', 'Auditoría al SGC'), ('z', 'Auditoría de la UEB Aeropuerto'), ('sga', 'Auditoría al SGA'), ('e', 'Auditoría de la Especialidad (UEB Nacionales)'), ('sgi', 'Auditoría al SGICH'), ('bv', 'Auditoría de Bureau Veritas'), ('ai', 'Auditoría Integrada')], max_length=3, verbose_name='Octubre')),
                ('n', models.CharField(blank=True, choices=[('nc', 'Auditoría Nivel Central'), ('sgc', 'Auditoría al SGC'), ('z', 'Auditoría de la UEB Aeropuerto'), ('sga', 'Auditoría al SGA'), ('e', 'Auditoría de la Especialidad (UEB Nacionales)'), ('sgi', 'Auditoría al SGICH'), ('bv', 'Auditoría de Bureau Veritas'), ('ai', 'Auditoría Integrada')], max_length=3, verbose_name='Noviembre')),
                ('d', models.CharField(blank=True, choices=[('nc', 'Auditoría Nivel Central'), ('sgc', 'Auditoría al SGC'), ('z', 'Auditoría de la UEB Aeropuerto'), ('sga', 'Auditoría al SGA'), ('e', 'Auditoría de la Especialidad (UEB Nacionales)'), ('sgi', 'Auditoría al SGICH'), ('bv', 'Auditoría de Bureau Veritas'), ('ai', 'Auditoría Integrada')], max_length=3, verbose_name='Diciembre')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Area', verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='AuditControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AuditInform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AuditPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralProgramAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField(verbose_name='Observaciones')),
                ('date', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.Audit', verbose_name='Auditoria')),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Elaborado por')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
