# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalprogramaudit',
            name='audit',
        ),
        migrations.AddField(
            model_name='audit',
            name='general_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='audit.GeneralProgramAudit', verbose_name='Programa general'),
            preserve_default=False,
        ),
    ]
