# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-21 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20170515_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audit',
            options={'verbose_name': 'Auditoria', 'verbose_name_plural': 'Auditorias'},
        ),
    ]
