# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('file', models.FileField(upload_to='', verbose_name='PDF')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='Fecha de Publicacion')),
            ],
            options={
                'verbose_name': 'Boletin',
                'verbose_name_plural': 'Boletines',
            },
        ),
    ]
