# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-15 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirLineRepresentPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalPassengerPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NationalPassengerPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(verbose_name='Su opinion')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Servicio')),
                ('evaluation', models.IntegerField(choices=[(0, 'No utilizado'), (1, 'Malo'), (2, 'Insatisfactorio'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], verbose_name='Evaluacion')),
                ('why', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='nationalpassengerpoll',
            name='services',
            field=models.ManyToManyField(related_name='Servicios', to='poll.Service'),
        ),
    ]
