# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internationalpassengerpoll',
            options={'verbose_name': 'Encuesta a Pasajeros Internacionales', 'verbose_name_plural': 'Encuestas a Pasajeros Internacionales'},
        ),
    ]
