# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalpassengerpoll',
            options={'verbose_name': 'Encuesta a Pasajeros Nacionales', 'verbose_name_plural': 'Encuestas a Pasajeros Nacionales'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='nationalpassengerpoll',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='national_passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poll.NationalPassengerPoll', verbose_name='Encuesta a Pasajeros Nacionales'),
            preserve_default=False,
        ),
    ]
