# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20170517_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirLineRepresentPoll',
        ),
    ]
