# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_delete_airlinerepresentpoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalpassengerpoll',
            name='date_out',
            field=models.DateField(default='2017-10-10', verbose_name='Fecha de salida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalpassengerpoll',
            name='nationality',
            field=models.CharField(default='Mexicano', max_length=100, verbose_name='Nacionalidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internationalpassengerpoll',
            name='no_flay',
            field=models.PositiveIntegerField(default='20171010', verbose_name='Numero de Vuelo'),
            preserve_default=False,
        ),
    ]
