# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20170518_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internationalpassengerpoll',
            old_name='no_flay',
            new_name='no_fly',
        ),
    ]
