# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20170518_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirLineRepresentPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fly_number', models.PositiveIntegerField(verbose_name='Numero de vuelo')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('team', models.CharField(max_length=100, verbose_name='Equipo')),
                ('no_position', models.PositiveIntegerField(verbose_name='Posicion No')),
                ('opinion', models.TextField(verbose_name='Opinion')),
            ],
        ),
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Aspecto a evaluar')),
                ('evaluation', models.CharField(choices=[(0, 'No utilizado'), (1, 'Malo'), (2, 'Insatisfactorio'), (3, 'Bueno'), (4, 'Muy Bueno'), (5, 'Excelente')], max_length=2, verbose_name='Evaluacion')),
                ('airline_represent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.AirLineRepresentPoll', verbose_name='Encuesta a representantes de Lineas Aereas')),
            ],
        ),
    ]
