# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_airlinerepresentpoll_aspect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airlinerepresentpoll',
            options={'verbose_name': 'Encuesta a representantes de Lineas Aereas', 'verbose_name_plural': 'Encuestas a representantes de Lineas Aereas'},
        ),
    ]
