# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20170519_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinerepresentpoll',
            name='opinion',
            field=models.TextField(blank=True, verbose_name='Opinion'),
        ),
    ]
