# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-19 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20170519_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('file', models.FileField(upload_to='', verbose_name='Ficheros')),
                ('classes', models.FileField(upload_to='', verbose_name='Ficheros de Clases')),
                ('pub_date', models.DateField(verbose_name='Fecha de publicacion')),
                ('register', models.ManyToManyField(related_name='register', to='account.Profile', verbose_name='Registar')),
            ],
            options={
                'verbose_name': 'Capacitacion',
                'verbose_name_plural': 'Capacitaciones',
            },
        ),
    ]
