# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='register',
            field=models.ManyToManyField(blank=True, related_name='register', to='account.Profile', verbose_name='Registar'),
        ),
    ]
