# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20170520_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='pub_date',
            field=models.DateField(auto_now=True, verbose_name='Fecha de publicacion'),
        ),
    ]
